### ISSUE TITLE
New version of C tmx map loader

### ISSUE THREAD

**Issue by Ozzyboshi** [alpine9000/climbyskies#1]
You should update your tools/mapgen/tmx.c because TMX v1.0.0 came out and there are some changes in tmx.h for example the tmx properties are no more on a linked list and the only way to navigate through them is using tmx_property_foreach() (no more next pointer) and other minor changes.
The only way to compile the game now is installing the previous release TMX v0.16.0 , with this release I successfully compiled all the files inside tools/mapgen.

**Comment by alpine9000** [comment]
Thanks for the report. I'll update it to work with the latest version.
